services:
  # 1. Das Test-DokuWiki
  # access api via: http://localhost:8080/lib/exe/openapi.php#?route=overview
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - dokuwiki-data:/config
      - ./docker/dokuwiki-config:/config/dokuwiki/conf
    ports:
      - "8080:80"
    restart: unless-stopped

  # 2. Unser Produktionsnaher MCP Server (API)
  # Dieser läuft auf Port 8000 für dein späteres Cloud-Deployment!
  dokuwiki-mcp:
    build:
      context: .                
      dockerfile: docker/Dockerfile
    container_name: dokuwiki_mcp
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DOKUWIKI_URL=http://dokuwiki
      # write token:
      #- DOKUWIKI_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkb2t1d2lraSIsInN1YiI6Im1jcC13cml0ZSIsImlhdCI6MTc3NTk0MzU1NH0=.hhQNhX96m2ZTEAg31mMZYNmiv/UDUQEva1WpE1puZbw=
    restart: unless-stopped

  # 3. Der Web Inspector (UI zum Debuggen)
  mcp-inspector:
    image: node:18-slim
    container_name: mcp_inspector
    ports:
      - "6274:6274"
      - "6277:6277"
    env_file:
      - .env
    environment:
      - DANGEROUSLY_OMIT_AUTH=true
    command: >
      npx -y @modelcontextprotocol/inspector
    restart: unless-stopped

volumes:
  dokuwiki-data:
