# ==============================================================================
# AUTO-GENERATED DOKUWIKI API CLIENT
# Do not edit this file manually. Regenerate using generate_client.py
# ==============================================================================
import httpx
import logging
from typing import Any, Dict, List, Optional, Union, Tuple
from pydantic import BaseModel, Field
from .config import get_settings

logger = logging.getLogger(__name__)

# --- BASE MODELS ---

class RPCError(BaseModel):
    """Informationen über einen API- oder Netzwerkfehler."""
    code: int = Field(..., description="Der Fehlercode (0 = Erfolg)")
    message: str = Field(..., description="Die Fehlermeldung")

# --- STRUCTURED RESULT MODELS ---

class getMediaHistoryResult(BaseModel):
    """Returns a list of available revisions of a given media file"""
    id: str = Field(default=None, description="""The media ID""")
    revision: int = Field(default=0, description="""The revision (timestamp) of this change""")
    author: str = Field(default=None, description="""The author of this change""")
    ip: str = Field(default=None, description="""The IP address from where this change was made""")
    summary: str = Field(default=None, description="""The summary of this change""")
    type: str = Field(default=None, description="""The type of this change""")
    sizechange: int = Field(default=0, description="""The change in bytes""")

class getMediaInfoResult(BaseModel):
    """Return info about a media file"""
    id: str = Field(default=None, description="""The media ID""")
    revision: int = Field(default=0, description="""The media revision aka last modified timestamp""")
    size: int = Field(default=0, description="""The page size in bytes""")
    permission: int = Field(default=0, description="""The current user's permissions for this file""")
    isimage: bool = Field(default=False, description="""Wether this is an image file""")
    hash: str = Field(default=None, description="""MD5 sum over the file's content (if available and requested)""")
    author: str = Field(default=None, description="""The author of this page revision (if available and requested)""")

class getPageHistoryResult(BaseModel):
    """Returns a list of available revisions of a given wiki page"""
    id: str = Field(default=None, description="""The page ID""")
    revision: int = Field(default=0, description="""The revision (timestamp) of this change""")
    author: str = Field(default=None, description="""The author of this change""")
    ip: str = Field(default=None, description="""The IP address from where this change was made""")
    summary: str = Field(default=None, description="""The summary of this change""")
    type: str = Field(default=None, description="""The type of this change""")
    sizechange: int = Field(default=0, description="""The change in bytes""")

class getPageInfoResult(BaseModel):
    """Return some basic data about a page"""
    id: str = Field(default=None, description="""The page ID""")
    revision: int = Field(default=0, description="""The page revision aka last modified timestamp""")
    size: int = Field(default=0, description="""The page size in bytes""")
    title: str = Field(default=None, description="""The page title""")
    permission: int = Field(default=0, description="""The current user's permissions for this page""")
    hash: str = Field(default=None, description="""MD5 sum over the page's content (if available and requested)""")
    author: str = Field(default=None, description="""The author of this page revision (if available and requested)""")

class getPageLinksResult(BaseModel):
    """Get a page's links"""
    type: str = Field(default=None, description="""The type of this link: `internal`, `external` or `interwiki`""")
    page: str = Field(default=None, description="""The wiki page this link points to, same as `href` for external links""")
    href: str = Field(default=None, description="""A hyperlink pointing to the linked target""")

class getRecentMediaChangesResult(BaseModel):
    """Get recent media changes"""
    id: str = Field(default=None, description="""The media ID""")
    revision: int = Field(default=0, description="""The revision (timestamp) of this change""")
    author: str = Field(default=None, description="""The author of this change""")
    ip: str = Field(default=None, description="""The IP address from where this change was made""")
    summary: str = Field(default=None, description="""The summary of this change""")
    type: str = Field(default=None, description="""The type of this change""")
    sizechange: int = Field(default=0, description="""The change in bytes""")

class getRecentPageChangesResult(BaseModel):
    """Get recent page changes"""
    id: str = Field(default=None, description="""The page ID""")
    revision: int = Field(default=0, description="""The revision (timestamp) of this change""")
    author: str = Field(default=None, description="""The author of this change""")
    ip: str = Field(default=None, description="""The IP address from where this change was made""")
    summary: str = Field(default=None, description="""The summary of this change""")
    type: str = Field(default=None, description="""The type of this change""")
    sizechange: int = Field(default=0, description="""The change in bytes""")

class listMediaResult(BaseModel):
    """List all media files in the given namespace (and below)"""
    id: str = Field(default=None, description="""The media ID""")
    revision: int = Field(default=0, description="""The media revision aka last modified timestamp""")
    size: int = Field(default=0, description="""The page size in bytes""")
    permission: int = Field(default=0, description="""The current user's permissions for this file""")
    isimage: bool = Field(default=False, description="""Wether this is an image file""")
    hash: str = Field(default=None, description="""MD5 sum over the file's content (if available and requested)""")
    author: str = Field(default=None, description="""The author of this page revision (if available and requested)""")

class listPagesResult(BaseModel):
    """List all pages in the given namespace (and below)"""
    id: str = Field(default=None, description="""The page ID""")
    revision: int = Field(default=0, description="""The page revision aka last modified timestamp""")
    size: int = Field(default=0, description="""The page size in bytes""")
    title: str = Field(default=None, description="""The page title""")
    permission: int = Field(default=0, description="""The current user's permissions for this page""")
    hash: str = Field(default=None, description="""MD5 sum over the page's content (if available and requested)""")
    author: str = Field(default=None, description="""The author of this page revision (if available and requested)""")

class searchPagesResult(BaseModel):
    """Do a fulltext search"""
    score: int = Field(default=0, description="""The number of hits this result got""")
    snippet: str = Field(default=None, description="""The HTML formatted snippet in which the search term was found (if available)""")
    hash: str = Field(default=None, description="""Not available for search results""")
    author: str = Field(default=None, description="""Not available for search results""")
    id: str = Field(default=None, description="""The page ID""")
    revision: int = Field(default=0, description="""The page revision aka last modified timestamp""")
    size: int = Field(default=0, description="""The page size in bytes""")
    title: str = Field(default=None, description="""The page title""")
    permission: int = Field(default=0, description="""The current user's permissions for this page""")

class whoAmIResult(BaseModel):
    """Info about the currently authenticated user"""
    login: str = Field(default=None, description="""The login name of the user""")
    name: str = Field(default=None, description="""The full name of the user""")
    mail: str = Field(default=None, description="""The email address of the user""")
    groups: List = Field(default=None, description="""The groups the user is in""")
    isadmin: bool = Field(default=False, description="""Whether the user is a super user""")
    ismanager: bool = Field(default=False, description="""Whether the user is a manager""")


# --- CLIENT IMPLEMENTATION ---

class DokuWikiClient:
    """
    High-level Pydantic-based client for DokuWiki JSON-RPC API.
    All methods return a Tuple of (Result, Error).
    """
    def __init__(self, username: Optional[str] = None, password: Optional[str] = None, token: Optional[str] = None):
        self.settings = get_settings()
        self.user = username or self.settings.dokuwiki_user
        self.pwd = password or self.settings.dokuwiki_password
        self.token = token or self.settings.dokuwiki_token
        self.auth = (self.user, self.pwd) if self.user and self.pwd else None
        self.headers = {"Authorization": f"Bearer {self.token}"} if self.token else {}

    async def _rpc_call(self, method: str, params: Dict[str, Any], response_model: Any = None) -> Tuple[Any, Optional[RPCError]]:
        base_url = self.settings.dokuwiki_url.rstrip("/")
        api_endpoint = f"{base_url}/lib/exe/jsonrpc.php/{method}"
        
        try:
            async with httpx.AsyncClient(auth=self.auth, headers=self.headers, timeout=30.0) as http_client:
                clean_params = {k: v for k, v in params.items() if v is not None}
                response = await http_client.post(api_endpoint, json=clean_params)
                response.raise_for_status() 
                data = response.json()
                
                rpc_err = None
                if isinstance(data, dict) and data.get("error"):
                    e = data["error"]
                    if isinstance(e, dict) and e.get("code") != 0:
                        rpc_err = RPCError(code=e.get("code", -1), message=e.get("message", "Unknown error"))
                
                if rpc_err:
                    return None, rpc_err

                result = data.get("result")
                if response_model and result is not None:
                    if isinstance(result, list):
                        return [response_model(**item) if isinstance(item, dict) else item for item in result], None
                    if isinstance(result, dict):
                        return response_model(**result), None
                
                return result, None
        except Exception as e:
            return None, RPCError(code=-999, message=str(e))

    async def aclCheck(self, page: str, user: str = "", groups: List = "[]") -> Tuple[Optional[int], Optional[RPCError]]:
        """Check ACL Permissions

        This call allows to check the permissions for a given page/media and user/group combination. If no user/group is given, the current user is used. Read the link below to learn more about the permission levels. **See also:** * [Acl Background Info](https://www.dokuwiki.org/acl#background_info)

        Args:
            page (str): A page or media ID
            user (str): username [_default: `""`_] (Default: "")
            groups (List): array of groups [_default: `[]`_] (Default: "[]")

        Returns:
            Tuple[Optional[int], Optional[RPCError]]: A tuple containing (Result: permission level, Error: RPCError object)
        """
        params = {
            "page": page,
            "user": user,
            "groups": groups,
        }
        return await self._rpc_call("core.aclCheck", params, None)

    async def appendPage(self, page: str, text: str, summary: str = "", isminor: bool = False) -> Tuple[Optional[bool], Optional[RPCError]]:
        """Appends text to the end of a wiki page

        If the page does not exist, it will be created. If a page template for the non-existant page is configured, the given text will appended to that template. The call will create a new page revision. You need write permissions for the given page.

        Args:
            page (str): page id
            text (str): wiki text
            summary (str): edit summary [_default: `""`_] (Default: "")
            isminor (bool): whether this is a minor edit [_default: `false`_] (Default: False)

        Returns:
            Tuple[Optional[bool], Optional[RPCError]]: A tuple containing (Result: Returns true on success, Error: RPCError object)
        """
        params = {
            "page": page,
            "text": text,
            "summary": summary,
            "isminor": isminor,
        }
        return await self._rpc_call("core.appendPage", params, None)

    async def deleteMedia(self, media: str) -> Tuple[Optional[bool], Optional[RPCError]]:
        """Deletes a file from the wiki

        You need to have delete permissions for the file.

        Args:
            media (str): media id

        Returns:
            Tuple[Optional[bool], Optional[RPCError]]: A tuple containing (Result: Should always be true, Error: RPCError object)
        """
        params = {
            "media": media,
        }
        return await self._rpc_call("core.deleteMedia", params, None)

    async def getAPIVersion(self) -> Tuple[Optional[int], Optional[RPCError]]:
        """Return the API version

        This method is public and does not require authentication. This is the version of the DokuWiki API. It increases whenever the API definition changes. When developing a client, you should check this version and make sure you can handle it.

        Returns:
            Tuple[Optional[int], Optional[RPCError]]: A tuple containing (Result: Return the API version, Error: RPCError object)
        """
        params = {
        }
        return await self._rpc_call("core.getAPIVersion", params, None)

    async def getMedia(self, media: str, rev: int = 0) -> Tuple[Optional[str], Optional[RPCError]]:
        """Get a media file's content

        Returns the content of the given media file. When no revision is given, the current revision is returned. **See also:** * https://en.wikipedia.org/wiki/Base64

        Args:
            media (str): file id
            rev (int): revision timestamp [_default: `0`_] (Default: 0)

        Returns:
            Tuple[Optional[str], Optional[RPCError]]: A tuple containing (Result: Base64 encoded media file contents, Error: RPCError object)
        """
        params = {
            "media": media,
            "rev": rev,
        }
        return await self._rpc_call("core.getMedia", params, None)

    async def getMediaHistory(self, media: str, first: int = 0) -> Tuple[Optional[List[getMediaHistoryResult]], Optional[RPCError]]:
        """Returns a list of available revisions of a given media file

        The number of returned files is set by `$conf['recent']`, but non accessible revisions are skipped, so less than that may be returned. Since API Version 14 @author **See also:** * [Config Recent](https://www.dokuwiki.org/config:recent)

        Args:
            media (str): file id
            first (int): skip the first n changelog lines, 0 starts at the current revision [_default: `0`_] (Default: 0)

        Returns:
            Tuple[Optional[List[getMediaHistoryResult]], Optional[RPCError]]: A tuple containing (Result: Returns a list of available revisions of a given media file, Error: RPCError object)
        """
        params = {
            "media": media,
            "first": first,
        }
        return await self._rpc_call("core.getMediaHistory", params, getMediaHistoryResult)

    async def getMediaInfo(self, media: str, rev: int = 0, author: bool = False, hash: bool = False) -> Tuple[Optional[getMediaInfoResult], Optional[RPCError]]:
        """Return info about a media file

        The call will return an error if the requested media file does not exist. Read access is required for the media file.

        Args:
            media (str): file id
            rev (int): revision timestamp [_default: `0`_] (Default: 0)
            author (bool): whether to include the author information [_default: `false`_] (Default: False)
            hash (bool): whether to include the MD5 hash of the media content [_default: `false`_] (Default: False)

        Returns:
            Tuple[Optional[getMediaInfoResult], Optional[RPCError]]: A tuple containing (Result: Return info about a media file, Error: RPCError object)
        """
        params = {
            "media": media,
            "rev": rev,
            "author": author,
            "hash": hash,
        }
        return await self._rpc_call("core.getMediaInfo", params, getMediaInfoResult)

    async def getMediaUsage(self, media: str) -> Tuple[Optional[List], Optional[RPCError]]:
        """Returns the pages that use a given media file

        The call will return an error if the requested media file does not exist. Read access is required for the media file. Since API Version 13

        Args:
            media (str): file id

        Returns:
            Tuple[Optional[List], Optional[RPCError]]: A tuple containing (Result: A list of pages linking to the given page, Error: RPCError object)
        """
        params = {
            "media": media,
        }
        return await self._rpc_call("core.getMediaUsage", params, None)

    async def getPage(self, page: str, rev: int = 0) -> Tuple[Optional[str], Optional[RPCError]]:
        """Get a wiki page's syntax

        Returns the syntax of the given page. When no revision is given, the current revision is returned. A non-existing page (or revision) will return an empty string usually. For the current revision a page template will be returned if configured. Read access is required for the page.

        Args:
            page (str): wiki page id
            rev (int): Revision timestamp to access an older revision [_default: `0`_] (Default: 0)

        Returns:
            Tuple[Optional[str], Optional[RPCError]]: A tuple containing (Result: the syntax of the page, Error: RPCError object)
        """
        params = {
            "page": page,
            "rev": rev,
        }
        return await self._rpc_call("core.getPage", params, None)

    async def getPageBackLinks(self, page: str) -> Tuple[Optional[List], Optional[RPCError]]:
        """Get a page's backlinks

        A backlink is a wiki link on another page that links to the given page. Only links from pages readable by the current user are returned. The page itself needs to be readable. Otherwise an error is returned.

        Args:
            page (str): page id

        Returns:
            Tuple[Optional[List], Optional[RPCError]]: A tuple containing (Result: A list of pages linking to the given page, Error: RPCError object)
        """
        params = {
            "page": page,
        }
        return await self._rpc_call("core.getPageBackLinks", params, None)

    async def getPageHTML(self, page: str, rev: int = 0) -> Tuple[Optional[str], Optional[RPCError]]:
        """Return a wiki page rendered to HTML

        The page is rendered to HTML as it would be in the wiki. The HTML consist only of the data for the page content itself, no surrounding structural tags, header, footers, sidebars etc are returned. References in the HTML are relative to the wiki base URL unless the `canonical` configuration is set. If the page does not exist, an error is returned. **See also:** * [Config Canonical](https://www.dokuwiki.org/config:canonical)

        Args:
            page (str): page id
            rev (int): revision timestamp [_default: `0`_] (Default: 0)

        Returns:
            Tuple[Optional[str], Optional[RPCError]]: A tuple containing (Result: Rendered HTML for the page, Error: RPCError object)
        """
        params = {
            "page": page,
            "rev": rev,
        }
        return await self._rpc_call("core.getPageHTML", params, None)

    async def getPageHistory(self, page: str, first: int = 0) -> Tuple[Optional[List[getPageHistoryResult]], Optional[RPCError]]:
        """Returns a list of available revisions of a given wiki page

        The number of returned pages is set by `$conf['recent']`, but non accessible revisions are skipped, so less than that may be returned. **See also:** * [Config Recent](https://www.dokuwiki.org/config:recent)

        Args:
            page (str): page id
            first (int): skip the first n changelog lines, 0 starts at the current revision [_default: `0`_] (Default: 0)

        Returns:
            Tuple[Optional[List[getPageHistoryResult]], Optional[RPCError]]: A tuple containing (Result: Returns a list of available revisions of a given wiki page, Error: RPCError object)
        """
        params = {
            "page": page,
            "first": first,
        }
        return await self._rpc_call("core.getPageHistory", params, getPageHistoryResult)

    async def getPageInfo(self, page: str, rev: int = 0, author: bool = False, hash: bool = False) -> Tuple[Optional[getPageInfoResult], Optional[RPCError]]:
        """Return some basic data about a page

        The call will return an error if the requested page does not exist. Read access is required for the page.

        Args:
            page (str): page id
            rev (int): revision timestamp [_default: `0`_] (Default: 0)
            author (bool): whether to include the author information [_default: `false`_] (Default: False)
            hash (bool): whether to include the MD5 hash of the page content [_default: `false`_] (Default: False)

        Returns:
            Tuple[Optional[getPageInfoResult], Optional[RPCError]]: A tuple containing (Result: Return some basic data about a page, Error: RPCError object)
        """
        params = {
            "page": page,
            "rev": rev,
            "author": author,
            "hash": hash,
        }
        return await self._rpc_call("core.getPageInfo", params, getPageInfoResult)

    async def getPageLinks(self, page: str) -> Tuple[Optional[List[getPageLinksResult]], Optional[RPCError]]:
        """Get a page's links

        This returns a list of links found in the given page. This includes internal, external and interwiki links If a link occurs multiple times on the page, it will be returned multiple times. Read access for the given page is needed and page has to exist.

        Args:
            page (str): page id

        Returns:
            Tuple[Optional[List[getPageLinksResult]], Optional[RPCError]]: A tuple containing (Result: A list of links found on the given page, Error: RPCError object)
        """
        params = {
            "page": page,
        }
        return await self._rpc_call("core.getPageLinks", params, getPageLinksResult)

    async def getRecentMediaChanges(self, timestamp: int = 0) -> Tuple[Optional[List[getRecentMediaChangesResult]], Optional[RPCError]]:
        """Get recent media changes

        Returns a list of recent changes to media files. The results can be limited to changes newer than a given timestamp. Only changes within the configured `$conf['recent']` range are returned. This is the default when no timestamp is given. **See also:** * [Config Recent](https://www.dokuwiki.org/config:recent)

        Args:
            timestamp (int): Only show changes newer than this unix timestamp [_default: `0`_] (Default: 0)

        Returns:
            Tuple[Optional[List[getRecentMediaChangesResult]], Optional[RPCError]]: A tuple containing (Result: Get recent media changes, Error: RPCError object)
        """
        params = {
            "timestamp": timestamp,
        }
        return await self._rpc_call("core.getRecentMediaChanges", params, getRecentMediaChangesResult)

    async def getRecentPageChanges(self, timestamp: int = 0) -> Tuple[Optional[List[getRecentPageChangesResult]], Optional[RPCError]]:
        """Get recent page changes

        Returns a list of recent changes to wiki pages. The results can be limited to changes newer than a given timestamp. Only changes within the configured `$conf['recent']` range are returned. This is the default when no timestamp is given. **See also:** * [Config Recent](https://www.dokuwiki.org/config:recent)

        Args:
            timestamp (int): Only show changes newer than this unix timestamp [_default: `0`_] (Default: 0)

        Returns:
            Tuple[Optional[List[getRecentPageChangesResult]], Optional[RPCError]]: A tuple containing (Result: Get recent page changes, Error: RPCError object)
        """
        params = {
            "timestamp": timestamp,
        }
        return await self._rpc_call("core.getRecentPageChanges", params, getRecentPageChangesResult)

    async def getWikiTime(self) -> Tuple[Optional[int], Optional[RPCError]]:
        """Return the current server time

        Returns a Unix timestamp (seconds since 1970-01-01 00:00:00 UTC). You can use this to compensate for differences between your client's time and the server's time when working with last modified timestamps (revisions).

        Returns:
            Tuple[Optional[int], Optional[RPCError]]: A tuple containing (Result: A unix timestamp, Error: RPCError object)
        """
        params = {
        }
        return await self._rpc_call("core.getWikiTime", params, None)

    async def getWikiTitle(self) -> Tuple[Optional[str], Optional[RPCError]]:
        """Returns the wiki title

        This method is public and does not require authentication. **See also:** * [Config Title](https://www.dokuwiki.org/config:title)

        Returns:
            Tuple[Optional[str], Optional[RPCError]]: A tuple containing (Result: Returns the wiki title, Error: RPCError object)
        """
        params = {
        }
        return await self._rpc_call("core.getWikiTitle", params, None)

    async def getWikiVersion(self) -> Tuple[Optional[str], Optional[RPCError]]:
        """Return DokuWiki's version

        This returns the version in the form "Type Date (SHA)". Where type is either "Release" or "Git" and date is the date of the release or the date of the last commit. SHA is the short SHA of the last commit - this is only added on git checkouts. If no version can be determined "snapshot? update version XX" is returned. Where XX represents the update version number set in doku.php.

        Returns:
            Tuple[Optional[str], Optional[RPCError]]: A tuple containing (Result: The version string e.g. "Release 2023-04-04a", Error: RPCError object)
        """
        params = {
        }
        return await self._rpc_call("core.getWikiVersion", params, None)

    async def listMedia(self, namespace: str = "", pattern: str = "", depth: int = 1, hash: bool = False) -> Tuple[Optional[List[listMediaResult]], Optional[RPCError]]:
        """List all media files in the given namespace (and below)

        Setting the `depth` to `0` and the `namespace` to `""` will return all media files in the wiki. When `pattern` is given, it needs to be a valid regular expression as understood by PHP's `preg_match()` including delimiters. The pattern is matched against the full media ID, including the namespace. **See also:** * https://www.php.net/manual/en/reference.pcre.pattern.syntax.php

        Args:
            namespace (str): The namespace to search. Empty string for root namespace [_default: `""`_] (Default: "")
            pattern (str): A regular expression to filter the returned files [_default: `""`_] (Default: "")
            depth (int): How deep to search. 0 for all subnamespaces [_default: `1`_] (Default: 1)
            hash (bool): Whether to include a MD5 hash of the media content [_default: `false`_] (Default: False)

        Returns:
            Tuple[Optional[List[listMediaResult]], Optional[RPCError]]: A tuple containing (Result: List all media files in the given namespace (and below), Error: RPCError object)
        """
        params = {
            "namespace": namespace,
            "pattern": pattern,
            "depth": depth,
            "hash": hash,
        }
        return await self._rpc_call("core.listMedia", params, listMediaResult)

    async def listPages(self, namespace: str = "", depth: int = 1, hash: bool = False) -> Tuple[Optional[List[listPagesResult]], Optional[RPCError]]:
        """List all pages in the given namespace (and below)

        Setting the `depth` to `0` and the `namespace` to `""` will return all pages in the wiki. Note: author information is not available in this call.

        Args:
            namespace (str): The namespace to search. Empty string for root namespace [_default: `""`_] (Default: "")
            depth (int): How deep to search. 0 for all subnamespaces [_default: `1`_] (Default: 1)
            hash (bool): Whether to include a MD5 hash of the page content [_default: `false`_] (Default: False)

        Returns:
            Tuple[Optional[List[listPagesResult]], Optional[RPCError]]: A tuple containing (Result: A list of matching pages, Error: RPCError object)
        """
        params = {
            "namespace": namespace,
            "depth": depth,
            "hash": hash,
        }
        return await self._rpc_call("core.listPages", params, listPagesResult)

    async def lockPages(self, pages: List) -> Tuple[Optional[List], Optional[RPCError]]:
        """Lock the given set of pages

        This call will try to lock all given pages. It will return a list of pages that were successfully locked. If a page could not be locked, eg. because a different user is currently holding a lock, that page will be missing from the returned list. You should always ensure that the list of returned pages matches the given list of pages. It's up to you to decide how to handle failed locking. Note: you can only lock pages that you have write access for. It is possible to create a lock for a page that does not exist, yet. Note: it is not necessary to lock a page before saving it. The `savePage()` call will automatically lock and unlock the page for you. However if you plan to do related operations on multiple pages, locking them all at once beforehand can be useful.

        Args:
            pages (List): A list of pages to lock

        Returns:
            Tuple[Optional[List], Optional[RPCError]]: A tuple containing (Result: A list of pages that were successfully locked, Error: RPCError object)
        """
        params = {
            "pages": pages,
        }
        return await self._rpc_call("core.lockPages", params, None)

    async def login(self, user: str, pass_: str) -> Tuple[Optional[int], Optional[RPCError]]:
        """Login

        This method is public and does not require authentication. This will use the given credentials and attempt to login the user. This will set the appropriate cookies, which can be used for subsequent requests. Use of this mechanism is discouraged. Using token authentication is preferred.

        Args:
            user (str): The user name
            pass_ (str): The password

        Returns:
            Tuple[Optional[int], Optional[RPCError]]: A tuple containing (Result: If the login was successful, Error: RPCError object)
        """
        params = {
            "user": user,
            "pass": pass_,
        }
        return await self._rpc_call("core.login", params, None)

    async def logoff(self) -> Tuple[Optional[int], Optional[RPCError]]:
        """Log off

        Attempt to log out the current user, deleting the appropriate cookies Use of this mechanism is discouraged. Using token authentication is preferred.

        Returns:
            Tuple[Optional[int], Optional[RPCError]]: A tuple containing (Result: 0 on failure, 1 on success, Error: RPCError object)
        """
        params = {
        }
        return await self._rpc_call("core.logoff", params, None)

    async def saveMedia(self, media: str, base64: str, overwrite: bool = False) -> Tuple[Optional[bool], Optional[RPCError]]:
        """Uploads a file to the wiki

        The file data has to be passed as a base64 encoded string. **See also:** * https://en.wikipedia.org/wiki/Base64

        Args:
            media (str): media id
            base64 (str): Base64 encoded file contents
            overwrite (bool): Should an existing file be overwritten? [_default: `false`_] (Default: False)

        Returns:
            Tuple[Optional[bool], Optional[RPCError]]: A tuple containing (Result: Should always be true, Error: RPCError object)
        """
        params = {
            "media": media,
            "base64": base64,
            "overwrite": overwrite,
        }
        return await self._rpc_call("core.saveMedia", params, None)

    async def savePage(self, page: str, text: str, summary: str = "", isminor: bool = False) -> Tuple[Optional[bool], Optional[RPCError]]:
        """Save a wiki page

        Saves the given wiki text to the given page. If the page does not exist, it will be created. Just like in the wiki, saving an empty text will delete the page. You need write permissions for the given page and the page may not be locked by another user.

        Args:
            page (str): page id
            text (str): wiki text
            summary (str): edit summary [_default: `""`_] (Default: "")
            isminor (bool): whether this is a minor edit [_default: `false`_] (Default: False)

        Returns:
            Tuple[Optional[bool], Optional[RPCError]]: A tuple containing (Result: Returns true on success, Error: RPCError object)
        """
        params = {
            "page": page,
            "text": text,
            "summary": summary,
            "isminor": isminor,
        }
        return await self._rpc_call("core.savePage", params, None)

    async def searchPages(self, query: str) -> Tuple[Optional[List[searchPagesResult]], Optional[RPCError]]:
        """Do a fulltext search

        This executes a full text search and returns the results. The query uses the standard DokuWiki search syntax. Snippets are provided for the first 15 results only. The title is either the first heading or the page id depending on the wiki's configuration. **See also:** * [Search Syntax](https://www.dokuwiki.org/search#syntax)

        Args:
            query (str): The search query as supported by the DokuWiki search

        Returns:
            Tuple[Optional[List[searchPagesResult]], Optional[RPCError]]: A tuple containing (Result: A list of matching pages, Error: RPCError object)
        """
        params = {
            "query": query,
        }
        return await self._rpc_call("core.searchPages", params, searchPagesResult)

    async def unlockPages(self, pages: List) -> Tuple[Optional[List], Optional[RPCError]]:
        """Unlock the given set of pages

        This call will try to unlock all given pages. It will return a list of pages that were successfully unlocked. If a page could not be unlocked, eg. because a different user is currently holding a lock, that page will be missing from the returned list. You should always ensure that the list of returned pages matches the given list of pages. It's up to you to decide how to handle failed unlocking. Note: you can only unlock pages that you have write access for.

        Args:
            pages (List): A list of pages to unlock

        Returns:
            Tuple[Optional[List], Optional[RPCError]]: A tuple containing (Result: A list of pages that were successfully unlocked, Error: RPCError object)
        """
        params = {
            "pages": pages,
        }
        return await self._rpc_call("core.unlockPages", params, None)

    async def whoAmI(self) -> Tuple[Optional[whoAmIResult], Optional[RPCError]]:
        """Info about the currently authenticated user

        Returns:
            Tuple[Optional[whoAmIResult], Optional[RPCError]]: A tuple containing (Result: Info about the currently authenticated user, Error: RPCError object)
        """
        params = {
        }
        return await self._rpc_call("core.whoAmI", params, whoAmIResult)

