import json
import re
import keyword
import os
from typing import Any, Dict, List, Optional
from jinja2 import Environment

# ============================================================================
# JINJA2 TEMPLATE (Annotated Type Registry & Models & Compact Docstrings)
# ============================================================================
CLIENT_TEMPLATE = """# ==============================================================================
# AUTO-GENERATED DOKUWIKI API CLIENT
# Do not edit this file manually. Regenerate using generate_client.py
# ==============================================================================
import httpx
import logging
from typing import Any, Dict, List, Optional, Union, Tuple, Annotated
from pydantic import BaseModel, Field
from .config import get_settings

logger = logging.getLogger(__name__)

# --- REUSABLE ANNOTATED TYPES ---
# Diese Typen definieren Struktur und Dokumentation zentral. 
# Importiere sie in deiner server.py für die MCP Tools!

{% for t in shared_types %}
{{ t.type_name }} = Annotated[{{ t.base_type }}, Field(title="{{ t.title }}", description={{ t.description }}{% if t.default_val is not none %}, default={{ t.default_val }}{% endif %}{% if t.examples %}, examples={{ t.examples }}{% endif %})]
{% endfor %}

# --- BASE MODELS ---

class RPCError(BaseModel):
    \"\"\"Informationen über einen API- oder Netzwerkfehler.\"\"\"
    code: int = Field(..., description=\"Der Fehlercode (0 = Erfolg)\")
    message: str = Field(..., description=\"Die Fehlermeldung\")

# --- STRUCTURED RESULT MODELS ---

{% for model in models %}
class {{ model.name }}(BaseModel):
    \"\"\"{{ model.description }}\"\"\"
{% for field in model.fields %}
    {{ field.name }}: {{ field.annotated_type }}
{% endfor %}

{% endfor %}

# --- CLIENT IMPLEMENTATION ---

class DokuWikiClient:
    \"\"\"
    High-level Pydantic-based client for DokuWiki JSON-RPC API.
    All methods return a Tuple of (Result, Error).
    \"\"\"
    def __init__(self, username: Optional[str] = None, password: Optional[str] = None, token: Optional[str] = None):
        self.settings = get_settings()
        self.user = username or self.settings.dokuwiki_user
        self.pwd = password or self.settings.dokuwiki_password
        self.token = token or self.settings.dokuwiki_token
        
        # Token has priority over username/password
        if self.token:
            self.auth = None
            self.headers = {"Authorization": f"Bearer {self.token}"}
        else:
            self.auth = (self.user, self.pwd) if self.user and self.pwd else None
            self.headers = {}

    async def _rpc_call(self, method: str, params: Dict[str, Any], response_model: Any = None) -> Tuple[Any, Optional[RPCError]]:
        base_url = self.settings.dokuwiki_url.rstrip("/")
        api_endpoint = f"{base_url}/lib/exe/jsonrpc.php/{method}"
        
        try:
            async with httpx.AsyncClient(auth=self.auth, headers=self.headers, timeout=30.0) as http_client:
                clean_params = {k: v for k, v in params.items() if v is not None}
                response = await http_client.post(api_endpoint, json=clean_params)
                response.raise_for_status() 
                data = response.json()
                
                rpc_err = None
                if isinstance(data, dict) and data.get("error"):
                    e = data["error"]
                    if isinstance(e, dict) and e.get("code") != 0:
                        rpc_err = RPCError(code=e.get("code", -1), message=e.get("message", "Unknown error"))
                
                if rpc_err:
                    return None, rpc_err

                result = data.get("result")
                if response_model and result is not None:
                    if isinstance(result, list):
                        return [response_model(**item) if isinstance(item, dict) else item for item in result], None
                    if isinstance(result, dict):
                        return response_model(**result), None
                
                return result, None
        except Exception as e:
            return None, RPCError(code=-999, message=str(e))

{% for m in methods %}
    async def {{ m.func_name }}(self{% if m.args_signature %}, {{ m.args_signature }}{% endif %}) -> Tuple[Optional[{{ m.result_type_hint }}], Optional[RPCError]]:
        \"\"\"{{ m.summary }}{% if m.description and m.description != m.summary %}: {{ m.description }}{% endif %}

        ---
        Returns: {{ m.result_desc }}
        \"\"\"
        params = {
{% for p in m.payload %}
            "{{ p.key }}": {{ p.val }},
{% endfor %}
        }
        return await self._rpc_call("{{ m.rpc_method }}", params, {{ m.response_class or 'None' }})

{% endfor %}
"""

def collapse_ws(text: str) -> str:
    if not text: return ""
    return re.sub(r'\s+', ' ', text).strip()

def map_type(openapi_type: str, item_type: str = None) -> str:
    mapping = {"string": "str", "integer": "int", "number": "float", "boolean": "bool", "array": "List", "object": "Dict[str, Any]"}
    base = mapping.get(openapi_type, "Any")
    return f"List[{item_type}]" if base == "List" and item_type else base

def extract_default(description: str, schema_default: Any) -> Optional[str]:
    # Direktes Schema-Default
    if schema_default is not None:
        if isinstance(schema_default, bool): return "True" if schema_default else "False"
        # Saubere Repräsentation für ints, floats, Listen und Dicts
        if isinstance(schema_default, (int, float, list, dict)): return repr(schema_default)
        return f'"{schema_default}"'
    
    # Textbasiertes Default aus Description
    match = re.search(r'\[_default:\s*(.*?)_\]', description)
    if match:
        val = match.group(1).strip().strip('`').strip('"').strip("'")
        if val.lower() == 'true': return "True"
        if val.lower() == 'false': return "False"
        # Behandle [] oder {} als native Objekte
        if val in ('[]', '{}'): return val
        # Behandle Zahlen
        if val.replace('.', '', 1).replace('-', '', 1).isdigit(): return val
        return f'"{val}"'
    return None

def to_camel_case(snake_str: str) -> str:
    components = re.split(r'[_:.-]', snake_str)
    return "".join(x.title() for x in components)

def generate_client(json_file: str, output_file: str):
    with open(json_file, 'r', encoding='utf-8') as f: spec = json.load(f)
    methods, models = [], {}
    
    # Globales Register für unsere Annotated Typen
    shared_types_registry = {}

    def register_type(prop_name: str, base_type: str, raw_desc: str, context: str, default_val: Optional[str] = None, examples: list = None) -> str:
        """Registriert einen Typ (Req oder Res) mit sauberen Field-Attributen."""
        type_name = f"{context}{to_camel_case(prop_name)}Type"
        clean_desc = re.sub(r'\[_default:\s*.*?_\]', '', raw_desc).strip()
        
        ex_val = examples or []
            
        if type_name not in shared_types_registry:
            shared_types_registry[type_name] = {
                "type_name": type_name,
                "title": prop_name,
                "base_type": base_type,
                # repr() sorgt dafür, dass aus dem String automatisch 'ein string mit quotes' wird
                "description": repr(clean_desc),
                "default_val": default_val,
                "examples": repr(ex_val) if ex_val else None
            }
        return type_name

    for path, data in sorted(spec.get("paths", {}).items()):
        if not path.startswith('/core.'): continue
        post = data["post"]
        m_name = path.replace("/core.", "")
        
        # --- RESPONSE PARSING ---
        res_schema_obj = post.get("responses", {}).get("200", {}).get("content", {}).get("application/json", {}).get("schema", {}).get("properties", {})
        result_schema = res_schema_obj.get("result", {})
        
        resp_class, type_hint, target, is_list = None, "Any", None, False
        if result_schema.get("type") == "object": target = result_schema
        elif result_schema.get("type") == "array" and result_schema.get("items", {}).get("type") == "object":
            target, is_list = result_schema["items"], True
            
        if target:
            resp_class = f"{to_camel_case(m_name)}Result"
            type_hint = f"List[{resp_class}]" if is_list else resp_class
            model_desc = collapse_ws(target.get("description") or post.get("summary") or f"Result for {m_name}")
            fields = []
            
            for fn, fp in target.get("properties", {}).items():
                ft = map_type(fp.get("type", "any"))
                f_desc_raw = collapse_ws(fp.get("description", "No description provided."))
                examples = fp.get("examples", [])
                def_val = extract_default(f_desc_raw, fp.get("default"))
                
                # Typ registrieren (Kontext: Res)
                annotated_type = register_type(fn, ft, f_desc_raw, "Res", def_val, examples)
                
                fields.append({
                    "name": fn if not keyword.iskeyword(fn) else f"{fn}_", 
                    "annotated_type": annotated_type, 
                    "default": def_val if def_val is not None else "None"
                })
            models[resp_class] = {"name": resp_class, "description": model_desc, "fields": fields}
        else: 
            # Primitive Response
            base_t = map_type(result_schema.get("type", "any"))
            f_desc_raw = collapse_ws(result_schema.get("description") or "API Result")
            def_val = extract_default(f_desc_raw, result_schema.get("default"))
            examples = result_schema.get("examples", [])
            
            if base_t != "Any":
                type_hint = register_type(m_name + "Result", base_t, f_desc_raw, "Res", def_val, examples)
            else:
                type_hint = base_t

        # --- PARAMS PARSING ---
        req_s = post.get("requestBody", {}).get("content", {}).get("application/json", {}).get("schema", {})
        props, req_f = req_s.get("properties", {}), set(req_s.get("required", []))
        args_s, payload = [], []
        param_names = sorted(props.keys(), key=lambda k: k not in req_f)
        
        for p in param_names:
            p_safe = f"{p}_" if keyword.iskeyword(p) else p
            pt = map_type(props[p].get("type", "any"))
            pd_raw = collapse_ws(props[p].get("description", ""))
            examples = props[p].get("examples", [])
            def_val = extract_default(pd_raw, props[p].get("default"))
            
            # Typ registrieren (Kontext: Req)
            annotated_type = register_type(p, pt, pd_raw, "Req", def_val, examples)
            
            if p in req_f:
                args_s.append(f"{p_safe}: {annotated_type}")
            else:
                # Fallback, falls weder im Text noch im Schema ein Default stand, aber Parameter optional ist
                dv = def_val if def_val is not None else ("False" if "bool" in pt else "0" if "int" in pt else "None")
                args_s.append(f"{p_safe}: {annotated_type} = {dv}")
            
            payload.append({"key": p, "val": p_safe})

        raw_res_desc = collapse_ws(result_schema.get("description") or post.get("summary") or "the API result")
        result_doc_desc = f"A tuple containing (Result: {raw_res_desc}, Error: RPCError object)"

        methods.append({
            "rpc_method": path.lstrip('/'), "func_name": m_name, 
            "summary": collapse_ws(post.get("summary", "No summary")), 
            "description": collapse_ws(post.get("description", "")),
            "result_type_hint": type_hint, "result_desc": result_doc_desc,
            "args_signature": ", ".join(args_s), "payload": payload, "response_class": resp_class
        })

    # Sortieren für konsistente Generierung
    shared_types_list = sorted(shared_types_registry.values(), key=lambda x: x["type_name"])

    env = Environment(trim_blocks=True, lstrip_blocks=True)
    with open(output_file, 'w', encoding='utf-8') as f: 
        f.write(env.from_string(CLIENT_TEMPLATE).render(
            methods=methods, 
            models=models.values(),
            shared_types=shared_types_list
        ))
    print(f"Client generiert: {output_file}")

if __name__ == "__main__":
    BASE = os.path.dirname(os.path.abspath(__file__))
    generate_client(os.path.join(BASE, "dokuwiki.json"), os.path.join(os.path.dirname(BASE), "src", "dokuwiki_mcp", "client.py"))