# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 11 Apr 2026 23:18:31 +0200
*	@ALL	1
*	@api	1
*	@read	1
*	@user	8
*	@write	16
