<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Sat, 11 Apr 2026 23:38:03 +0200
 */

$conf['title'] = 'DokuWiki MCP Test Instance';
$conf['license'] = '0';
$conf['savedir'] = '/app/www/public/data';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['remote'] = 1;
$conf['remoteuser'] = '@api';
$conf['remotecors'] = '*';
