<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Sat, 11 Apr 2026 23:18:31 +0200
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
