# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 11 Apr 2026 23:18:31 +0200
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

root:$2y$10$PDpVpxy4a4ePDkh64OV6EuO55KJHziR8dORc8izremMgUObx5AhxC:root:root@root.com:admin,user
mcp-read:$2y$10$otwrcEd3s2gTJIREbtosZ.45uk/VMMZw8aUEb2MohR8A1BhdhVwlm:mcp-read:mcp@read.com:api,read
mcp-write:$2y$10$pdRCEEqQbqMRADA7xCS25OAn3AZuTsa18dfrG5sZB2lfLCFvKsfwq:mcp-write:mcp@write.com:api,write
